apiVersion: v1
kind: Service
metadata:
  name: artemis-postgres-svc
  namespace: default
spec:
  selector:
    app: artemis-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: artemis-redis-svc
  namespace: default
spec:
  selector:
    app: artemis-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: artemis-grafana-svc
  namespace: default
spec:
  selector:
    app: artemis-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer