apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: artemis-ui-role
rules:
  - apiGroups: ["krishoperator.dev"]
    resources: ["apiservices"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: artemis-ui-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: artemis-ui-role
  apiGroup: rbac.authorization.k8s.io